services:
    express: 
        build: .
        networks:
            - net
        ports: 
            - ${PORT}:${PORT}
        depends_on: 
            - postgres
        environment: 
            - PORT=${PORT}
        volumes: 
            - ./src:/usr/app/src
            - ./log:/usr/app/log
        restart: always
    postgres:
        build: ./database/
        networks:
            - net
        ports: 
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        environment: 
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
networks:
    net:
        driver: bridge
        ipam:
            driver: default
